### ISSUE TITLE
The graphics are very pixelated?

### ISSUE THREAD

**Issue by user648** [HuniePotHeads/HuniePop-x64#2]
**Describe the bug**
The game runs fine, but the graphics are extremely pixelated.

**To Reproduce**
I booted up the game.

**Expected behavior**
The graphics not to be pixelated.

**Screenshots and logs**

![image](https://user-images.githubusercontent.com/77226719/104118803-8c597100-5390-11eb-8ed5-f702646f38e8.png)

okay the screenshot doesnt look like it's very pixelated but it is. 

**System information (please fill out as many questions as you can):**
 - Game version: HuniePop 1.2.0 Humble Bundle 64bit
 - System OS: macOS Big Sur - but was the same on Catalina 
 - 
**Additional context**

**Comment by user648** [comment]
Okay this is weird. When i compare the screenshot next to the game, the game looks like the colours have been turned up, kyu's hair is more clourful and it is more pixelated on the actual game. whack.

**Comment by TheLounger** [comment]
Thanks for the report.
I can see the pixelation in your screenshot, but I'm not sure yet what the culprit is.
It could be an issue with macOS, your graphics card and/or drivers, or with the Unity engine in general (HuniePop uses a very old Unity version from 2013.)
I'll do some investigating 👍
Could you post your graphics information? Like what graphics card (GPU), driver, OpenGL and Metal information... All of this can be found under System Report.

**Comment by MORADNAXOSH** [comment]
When I try to merge the files, the only options I get are "Stop" and "Replace". I'm also given the "do not have permission to open this" message when I try to use it. And when I'm trying to open huniepop, it gives me the same steam message it always does which is "Mac OS no longer supports 32-bit apps". Please help and thank you very much.
